---
mappings:
- alias: "/brzoskwin-17843a/CbCR Tax Rate Analysis/audit_flags"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.db46c797-642f-4c07-a41c-6490edee1409"
- alias: "/brzoskwin-17843a/CbCR Tax Rate Analysis/cbcr_clean"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e3d5b917-7337-44d7-a66e-b6afa00fdb5b"
- alias: "/brzoskwin-17843a/CbCR Tax Rate Analysis/cbcr_incremental_snapshot"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8009214f-f3ac-4aeb-a693-d6afdcae90d3"
- alias: "/brzoskwin-17843a/CbCR Tax Rate Analysis/effective_vs_statutory"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.104d8aa5-0607-4208-a943-0b6202c90a74"
- alias: "/brzoskwin-17843a/CbCR Tax Rate Analysis/tax_rates_clean"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.9993b1bd-40b8-4c15-8218-a0077a6e095a"
- alias: "/brzoskwin-17843a/CbCR Tax Rate Analysis/tax_rates_raw"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a1bb8247-a921-4b36-b30c-026d512d03dc"
- alias: "ri.foundry.main.dataset.19cf92fd-547c-4ded-8444-c7baf6666305"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.19cf92fd-547c-4ded-8444-c7baf6666305"
- alias: "ri.foundry.main.dataset.e3d5b917-7337-44d7-a66e-b6afa00fdb5b"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e3d5b917-7337-44d7-a66e-b6afa00fdb5b"
- alias: "ri.magritte..source.2183349f-f442-4f9c-8da6-dd4af6a0278b"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.magritte..source.2183349f-f442-4f9c-8da6-dd4af6a0278b"
